spring:
  redis:
    password: ''
    database: '0'
    ssl: 'false'
    host: localhost
    port: '6379'
  cache:
    type: redis
    redis:
      cache-null-values: 'true'

  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/musicAppdb
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
server:
  port: '8090'

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,health,info'

