spring:
  redis:
    password: ''
    database: '0'
    ssl: 'false'
    host: localhost
    port: '6379'
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/musicAppdb
    password: '123456'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      javax:
        persistence:
          validation:
            mode: none
    hibernate:
      ddl-auto: update
server:
  port: '8090'

jwt:
  secretKey: abcdefgeggebzbzbzbzbzbzbzbzbzbzbzbzzzzzzzzbbbbbbbbbbzbbbbbbbbbbbzbbbbbbbbbbbbbzbbbbbbbbbbbzbbbbbbb
  tokenValidityInSeconds: 36000000
