GET http://localhost:8090/actuator/prometheus
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZDNhMmFjNS01ODVkLTQwMWItODhkNy01YzEyOWI1MGFhYTgiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2OTA4ODQ5OTcsImV4cCI6MTY5MDg4NzU4OX0.-jCI0sDbsQSfgZJYgl3xnO-mj_B9s_YUN0oakiG9DFlLMyB6KGPKcwdCsmYGbC3OI7nD0laTjiQLCo871ysMfA
###
GET http://localhost:8090/actuator/beans
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZDNhMmFjNS01ODVkLTQwMWItODhkNy01YzEyOWI1MGFhYTgiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2OTA4Nzg4MjcsImV4cCI6MTY5MDg4MTQxOX0.9OSGJRT39ebx02LjT-vEwJDaQb20_14HAlf1D-vpF_vqVAiqmJnGIc7sCah7VDnHHgZy-ZFprftl9DYnu-OA4g

###
GET http://localhost:8090/actuator/loggers
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJkZDNhMmFjNS01ODVkLTQwMWItODhkNy01YzEyOWI1MGFhYTgiLCJyb2xlcyI6WyJBRE1JTiJdLCJpYXQiOjE2OTA4Nzg4MjcsImV4cCI6MTY5MDg4MTQxOX0.9OSGJRT39ebx02LjT-vEwJDaQb20_14HAlf1D-vpF_vqVAiqmJnGIc7sCah7VDnHHgZy-ZFprftl9DYnu-OA4g


